//! The CODEOWNERS governance block (pure text generation, no network).
//!
//! `bastion github codeowners` prints a CODEOWNERS block that assigns the
//! reviewer-policy paths to the given owners, so any PR that touches review policy
//! (the registry, the workflow, or CODEOWNERS itself) requires a human review. See
//! the governance section of `docs/developer-guide/github-adapter.md`.

use crate::config;

/// Render the CODEOWNERS block assigning `owners` to the reviewer-policy paths.
///
/// Covers the reviewer registry (both the `.yaml` and `.yml` spellings), the
/// Bastion workflow, and the CODEOWNERS file itself (in both common locations),
/// plus `extra_paths`: the repo-relative, slash-separated files the registry
/// pulls in (included registries and prompt files), which carry policy exactly
/// like the root file.
#[must_use]
pub fn block(owners: &[String], extra_paths: &[String]) -> String {
    let owners = owners.join(" ");
    let mut block = format!(
        "# Bastion reviewer policy: changes here require human review.\n\
         # Generated by `bastion github codeowners`; commit this into .github/CODEOWNERS (or your CODEOWNERS).\n\
         /{registry_yaml} {owners}\n\
         /{registry_yml} {owners}\n\
         /.github/workflows/bastion.yml {owners}\n\
         /CODEOWNERS {owners}\n\
         /.github/CODEOWNERS {owners}\n",
        registry_yaml = config::REGISTRY_FILES[0],
        registry_yml = config::REGISTRY_FILES[1],
    );
    for path in extra_paths {
        block.push('/');
        block.push_str(path);
        block.push(' ');
        block.push_str(&owners);
        block.push('\n');
    }
    block
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn block_covers_policy_paths() {
        let block = block(&["@acme/platform".into(), "@jess".into()], &[]);
        assert!(block.contains("/.bastion.yaml @acme/platform @jess"));
        assert!(block.contains("/.bastion.yml @acme/platform @jess"));
        assert!(block.contains("/.github/workflows/bastion.yml @acme/platform @jess"));
        assert!(block.contains("/CODEOWNERS @acme/platform @jess"));
        assert!(block.contains("require human review"));
        // No em or en dashes in the generated block.
        assert!(!block.contains('\u{2014}') && !block.contains('\u{2013}'));
    }

    #[test]
    fn block_covers_the_registry_pulled_in_files() {
        // Included registries and prompt files are policy like the root file, so
        // each extra path gets its own root-anchored entry.
        let block = block(
            &["@acme/platform".into()],
            &[
                "reviewers/security.yaml".into(),
                "reviewers/prompts/tenant-isolation.md".into(),
            ],
        );
        assert!(block.contains("/reviewers/security.yaml @acme/platform"));
        assert!(block.contains("/reviewers/prompts/tenant-isolation.md @acme/platform"));
    }
}
