//! Loading the reviewer registry from disk.
//!
//! Reviewers are declarative and static, defined in a `.bastion.yaml` (or
//! `.bastion.yml`) file at the repository root, under a `reviewers:` key. Keeping
//! them on disk (not generated by code) is what makes them reviewable and gives a
//! stable trigger set.
//!
//! A registry can spread across files without changing what it means. A top-level
//! `include:` array names further registry files (recursively) whose reviewers
//! merge into the including file's, and a reviewer's `prompt` can be a
//! `{file: <path>}` reference to a markdown file instead of inline text. Loading
//! resolves both, so past this module the system sees one flat [`Config`] whose
//! reviewers carry their actual prompt text; the effective hash and everything
//! downstream bind the resolved content, not the file layout.
//!
//! Locally, reviewers can also come from a user-level `.bastion.yaml` in the
//! platform config directory ([`user_config_dir`]). [`Config::discover_merged`]
//! layers it onto the repository's so a personal reviewer runs even when a repo has
//! not adopted Bastion; CI, which has no user config directory, sees the repository
//! set alone. Includes stay within their layer: a user-file include merges into the
//! user layer, a repo-file include (and any `--include` passed on the command line)
//! into the repository layer.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use color_eyre::eyre::{Context, Result, bail, eyre};
use serde::{Deserialize, Serialize};
use sha2::Digest;

use crate::limits::SpawnLimits;
use crate::reviewer::{Backend, Effort, ModelId, PromptSource, Reviewer};

/// The canonical registry file name at the repository root.
pub const REGISTRY_FILE: &str = ".bastion.yaml";

/// The registry file names discovery accepts, in precedence order. Both the
/// `.yaml` and `.yml` spellings are honored; if both exist in the same directory,
/// `.bastion.yaml` wins.
pub const REGISTRY_FILES: [&str; 2] = [".bastion.yaml", ".bastion.yml"];

/// The deprecated pre-rename registry location (`bastion/reviewers.yaml`),
/// relative to the repository root.
///
/// Discovery still finds it, with the lowest precedence, so existing repositories
/// keep working: a directory's `.bastion.yaml`/`.bastion.yml` wins over this, and a
/// closer ancestor wins over a farther one. When it is the file that resolves,
/// [`Config::discover`] logs a deprecation warning pointing at [`REGISTRY_FILE`].
/// This shim will be removed in a future release.
pub const LEGACY_REGISTRY_RELPATH: &str = "bastion/reviewers.yaml";

/// Environment variable that overrides the user-level config directory (where a
/// personal `.bastion.yaml` lives). Mirrors [`crate::paths::DATA_DIR_ENV`]; used in
/// tests and by anyone who wants their reviewers read from a specific directory.
pub const CONFIG_DIR_ENV: &str = "BASTION_CONFIG_DIR";

/// The scope sentinel prepended to a *repository* reviewer's name when a user-level
/// reviewer of the same name carries a different config, so both survive the merge
/// distinctly (the user's keeps the plain name, the repo's becomes
/// `repo:<name>`). It disambiguates rather than drops, since the two registries are
/// authored independently and a user must be able to run their own reviewer locally
/// regardless of the repo's. A fully identical pair is deduplicated instead, so the
/// sentinel only ever marks a genuine difference. The colon is a display detail; the
/// run store maps it to a portable path component (see [`crate::paths`]).
pub const REPO_SCOPE_PREFIX: &str = "repo:";

/// Resolve the user-level config directory by platform convention, honoring
/// [`CONFIG_DIR_ENV`] when set:
///
/// - Linux: `$XDG_CONFIG_HOME/bastion` (default `~/.config/bastion`)
/// - macOS: `~/Library/Application Support/bastion`
/// - Windows: `%APPDATA%\bastion`
///
/// Returns `None` only when no override is set and no home directory can be
/// determined, in which case there is simply no user-level registry to layer in.
/// This is the platform config dir, a sibling of the data dir [`crate::paths`]
/// resolves for run history.
#[must_use]
pub fn user_config_dir() -> Option<PathBuf> {
    if let Some(over) = std::env::var_os(CONFIG_DIR_ENV).filter(|v| !v.is_empty()) {
        return Some(PathBuf::from(over));
    }
    directories::BaseDirs::new().map(|base| base.config_dir().join("bastion"))
}

/// The loaded reviewer registry: one flat set of reviewers with every file-layout
/// concern (includes, prompt files, per-file defaults) already resolved away.
///
/// This is deliberately not the deserialization target ([`RawFile`] is): a
/// `Config` in hand means prompts are actual text and includes are merged, so no
/// consumer can observe a half-resolved registry.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Config {
    /// Whether this repository accepts a signed local attestation in place of
    /// re-executing a reviewer in CI (`docs/developer-guide/attestation.md`).
    /// Default off: CI ignores any attestation note entirely until a repository
    /// opts in explicitly. Only the root registry file may set this; an included
    /// file that tries is a load error rather than a silent no-op.
    pub attestations: bool,
    /// The per-run agent-launch caps ([`SpawnLimits`]) the runner enforces for a
    /// review of this repository, bounding how much a single `bastion review` can
    /// spend on its agent fan-out. Only the root registry file may set them (like
    /// `attestations`); any field left out takes its conservative default, and a
    /// registry with no `limits:` block at all runs fully capped by the defaults.
    /// They do not move the attestation hash: a cap is an operational safety net,
    /// not review policy that changes what a reviewer concludes.
    pub limits: SpawnLimits,
    /// The reviewers defined for this repository, in file order: the root file's
    /// first, then each include's (depth-first, in `include:` order).
    pub reviewers: Vec<Reviewer>,
}

/// Registry-wide defaults applied to every reviewer at load time.
///
/// A reviewer's own field always wins; these fill the gaps. They sit *above* each
/// backend's built-in default (Opus 4.8 at high effort for Claude Code), so a repo
/// can set a house model and effort in one place without repeating them on every
/// reviewer. In a multi-file registry each file's `defaults:` apply to the
/// reviewers declared in that same file only, so an included file means the same
/// thing no matter who includes it.
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
#[non_exhaustive]
pub struct Defaults {
    /// Default model for reviewers that do not pin one. Like a reviewer's own
    /// `model`, this is backend-specific: a reviewer that inherits it must pin a
    /// backend (the registry rejects an inherited model under `backend: any`).
    #[serde(default)]
    pub model: Option<ModelId>,
    /// Default reasoning effort for reviewers that do not set one.
    #[serde(default)]
    pub effort: Option<Effort>,
}

/// One registry file as deserialized, before prompts and includes resolve.
///
/// `attestations` is an `Option` (not a defaulted `bool`) so loading can tell "the
/// file says nothing" from "the file explicitly sets it": only the root file may
/// set it at all, and an included file that tries must fail loudly.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RawFile {
    #[serde(default)]
    defaults: Defaults,
    #[serde(default)]
    attestations: Option<bool>,
    /// The per-run spend caps. Like `attestations`, an `Option` so loading can
    /// tell "the file says nothing" (defaults apply) from "the file sets them",
    /// and only the root file may set them.
    #[serde(default)]
    limits: Option<SpawnLimits>,
    /// Further registry files to merge in, resolved relative to this file's
    /// directory. Includes recurse; a file reached twice (a diamond, or a cycle)
    /// merges once.
    #[serde(default)]
    include: Vec<PathBuf>,
    #[serde(default)]
    reviewers: Vec<Reviewer<PromptSource>>,
}

/// The files a single registry layer was assembled from, beyond its root file.
///
/// Loading records these so callers can report exactly what fed the merged set:
/// `bastion validate` lists them, and `bastion github codeowners` protects them,
/// since an included registry or a prompt file is review policy exactly like the
/// root `.bastion.yaml`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct LayerFiles {
    /// Registry files merged in via `include:` (or `--include`), in merge order.
    pub includes: Vec<PathBuf>,
    /// Prompt files read for `prompt: {file: ...}` reviewers, in load order.
    pub prompts: Vec<PathBuf>,
}

impl LayerFiles {
    /// Whether the layer was a single self-contained file.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.includes.is_empty() && self.prompts.is_empty()
    }
}

/// Load state threaded through one registry layer's include tree.
struct Loader {
    /// Canonical paths of registry files already merged, so a diamond include
    /// merges once and a cycle terminates instead of recursing.
    visited: BTreeSet<PathBuf>,
    /// The file trail recorded for [`LayerFiles`].
    files: LayerFiles,
    /// Which file declared each reviewer name, so a duplicate across the merged
    /// layer errors naming both files, not just the one hit second.
    origins: std::collections::BTreeMap<String, String>,
}

impl Config {
    /// Parse a registry from YAML text, resolving prompt files and includes
    /// relative to `dir` and validating the merged result (reviewer-name
    /// uniqueness among the rest).
    ///
    /// # Errors
    ///
    /// Returns an error if the YAML is malformed, a prompt file or included
    /// registry cannot be read, or the merged set fails validation.
    pub fn from_yaml(yaml: &str, dir: &Path) -> Result<Self> {
        let raw: RawFile =
            serde_yaml_ng::from_str(yaml).wrap_err("reviewer registry is not valid YAML")?;
        let mut loader = Loader::new();
        let mut config = Config::default();
        loader.merge_file(raw, dir, "the reviewer registry", true, &mut config)?;
        config.validate()?;
        Ok(config)
    }

    /// Load and parse the registry at `path`, resolving its prompt files and
    /// includes relative to it.
    ///
    /// # Errors
    ///
    /// Returns an error if any involved file cannot be read or parsed, or the
    /// merged set fails validation.
    pub fn load(path: &Path) -> Result<Self> {
        Self::load_layer(path, &[]).map(|(config, _)| config)
    }

    /// Like [`Config::load`], but with extra registry files merged in as if the
    /// root file's `include:` array listed them (the `--include` flag), and
    /// returning the [`LayerFiles`] trail of every file beyond the root that fed
    /// the result.
    ///
    /// # Errors
    ///
    /// Returns an error if any involved file cannot be read or parsed, an
    /// included file sets `attestations`, or the merged set fails validation.
    pub fn load_layer(path: &Path, extra_includes: &[PathBuf]) -> Result<(Self, LayerFiles)> {
        let mut loader = Loader::new();
        // Best effort: mark the root so an include that cycles back to it merges
        // nothing instead of loading it twice. A canonicalization failure is not
        // an error here; the read below reports the real problem with context.
        if let Ok(canonical) = std::fs::canonicalize(path) {
            loader.visited.insert(canonical);
        }
        let raw = read_registry(path)?;
        let dir = base_dir(path);
        let label = path.display().to_string();
        let mut config = Config::default();
        loader.merge_file(raw, &dir, &label, true, &mut config)?;
        for include in extra_includes {
            loader.include(include, "the command line (--include)", &mut config)?;
        }
        config.validate()?;
        Ok((config, loader.files))
    }

    /// Assemble a registry layer purely from `--include` files, for a run with
    /// no root registry to hang them off (a repository that has not adopted
    /// Bastion, reviewed with explicitly passed files).
    ///
    /// # Errors
    ///
    /// Returns an error if any file cannot be read or parsed, sets
    /// `attestations`, or the merged set fails validation.
    pub(crate) fn layer_from_includes(extra_includes: &[PathBuf]) -> Result<(Self, LayerFiles)> {
        let mut loader = Loader::new();
        let mut config = Config::default();
        for include in extra_includes {
            loader.include(include, "the command line (--include)", &mut config)?;
        }
        config.validate()?;
        Ok((config, loader.files))
    }

    /// Discover and load the registry by walking up from `start` looking for a
    /// `.bastion.yaml` (or `.bastion.yml`) at each ancestor directory.
    ///
    /// Falls back to the deprecated [`LEGACY_REGISTRY_RELPATH`] location, logging a
    /// deprecation warning when that is what resolves.
    ///
    /// # Errors
    ///
    /// Returns an error if no registry is found in any ancestor directory, or if
    /// the discovered file fails to load.
    pub fn discover(start: &Path) -> Result<Self> {
        Self::discover_located(start).map(|(_, config)| config)
    }

    /// Like [`Config::discover`], but also returns the [`Found`] location the
    /// registry was loaded from. A caller that needs both the parsed config and its
    /// path (to report it, say) takes them from one discovery rather than walking the
    /// tree a second time, so the path it reports cannot disagree with the file it
    /// parsed.
    ///
    /// # Errors
    ///
    /// Returns an error if no registry is found in any ancestor directory, or if
    /// the discovered file fails to load.
    pub fn discover_located(start: &Path) -> Result<(Found, Self)> {
        let found = locate_kind(start)?.ok_or_else(|| {
            eyre!(
                "no reviewer registry found; expected {} (or {}) in this repo or an ancestor",
                REGISTRY_FILES[0],
                REGISTRY_FILES[1],
            )
        })?;
        if found.deprecated {
            tracing::warn!(
                "reviewer registry found at the deprecated path `{}`; rename it to `{}` at the repository root. The old location still works for now but will stop being read in a future release.",
                LEGACY_REGISTRY_RELPATH,
                REGISTRY_FILE,
            );
        }
        let config = Self::load(&found.path)?;
        Ok((found, config))
    }

    /// Discover the merged registry `bastion review` runs: the repository registry
    /// (walked up from `start`) with the user-level registry (in `user_dir`)
    /// layered beneath it, so a reviewer a user keeps in their config dir runs
    /// locally whether or not the repository adopts Bastion in CI.
    ///
    /// `user_dir` is the resolved user config directory ([`user_config_dir`]), or
    /// `None` to skip the user-level layer entirely. Either source may be absent;
    /// only the absence of *both* is an error.
    ///
    /// # Errors
    ///
    /// Returns an error if neither a repository nor a user-level registry is found,
    /// if a candidate path cannot be inspected (a stat error other than not-found),
    /// if a discovered file fails to load, or if the merged set fails validation.
    pub fn discover_merged(start: &Path, user_dir: Option<&Path>) -> Result<Self> {
        Self::discover_merged_located(start, user_dir, &[]).map(|(_, config)| config)
    }

    /// Like [`Config::discover_merged`], but also returns the [`Sources`] the merged
    /// config was built from, so a caller (such as `bastion validate`) can report
    /// exactly which files fed it.
    ///
    /// The repository registry is loaded as the base, then the user-level reviewers
    /// are merged onto it as a set: an identical reviewer in both files is
    /// deduplicated, and a same-name-different-config collision keeps both with the
    /// repo side scoped to [`REPO_SCOPE_PREFIX`] (the merge is `layer_user`). The
    /// merged set is re-validated so a residual duplicate name fails closed.
    ///
    /// # Errors
    ///
    /// Returns an error if neither a repository nor a user-level registry is found,
    /// if a candidate path cannot be inspected (a stat error other than not-found,
    /// from [`locate_kind`] or [`locate_user`]), if a discovered file fails to load,
    /// or if the merged set fails validation.
    pub fn discover_merged_located(
        start: &Path,
        user_dir: Option<&Path>,
        extra_includes: &[PathBuf],
    ) -> Result<(Sources, Self)> {
        Self::discover_merged_attested(start, user_dir, extra_includes)
            .map(|(sources, _, config)| (sources, config))
    }

    /// Like [`Config::discover_merged_located`], but also returns a
    /// [`RepoAttestation`] describing the *repository-only* effective config: its
    /// hash (before the user-level registry is layered in) and the set of
    /// reviewer names that came from the repository registry.
    ///
    /// An attestation binds the effective *repository* reviewer config
    /// (`docs/developer-guide/attestation.md`): the user-level registry is
    /// deliberately excluded, since a personal reviewer never gates anyone
    /// else's PR and so cannot attest anything either. Computing the hash here,
    /// on the repo-only `Config` after `apply_defaults` but before
    /// `layer_user`, is what keeps that exclusion exact: the returned hash and
    /// reviewer set reflect only what the repository itself declares.
    ///
    /// A repository reviewer that collides with a user reviewer of the same
    /// name gets scoped to `repo:<name>` by `layer_user`; `reviewers` here
    /// already carries that scoped name; so a caller filtering a run's resolved
    /// events down to "reviewers this seal covers" matches by the same names the
    /// merged config exposes.
    ///
    /// `extra_includes` are registry files merged into the *repository* layer as
    /// if the repository root file's `include:` array listed them (the
    /// `--include` flag). They are part of the effective repository config, so
    /// they move the attestation hash; a run reviewed with extra includes only
    /// replays in CI if CI passes the same files.
    ///
    /// # Errors
    ///
    /// Returns an error if neither a repository nor a user-level registry is
    /// found (and no extra include is given), if a candidate path cannot be
    /// inspected, if a discovered file fails to load, or if the merged set fails
    /// validation.
    pub fn discover_merged_attested(
        start: &Path,
        user_dir: Option<&Path>,
        extra_includes: &[PathBuf],
    ) -> Result<(Sources, RepoAttestation, Self)> {
        let repo = locate_kind(start)?;
        let user = match user_dir {
            Some(dir) => locate_user(dir)?,
            None => None,
        };

        if repo.is_none() && user.is_none() && extra_includes.is_empty() {
            bail!(
                "no reviewer registry found; expected {} (or {}) in this repo or an ancestor{}",
                REGISTRY_FILES[0],
                REGISTRY_FILES[1],
                user_dir.map_or_else(String::new, |dir| format!(
                    ", or {} in your user config directory ({})",
                    REGISTRY_FILE,
                    dir.display()
                )),
            );
        }

        let (mut config, repo_files) = match &repo {
            Some(found) => {
                if found.deprecated {
                    tracing::warn!(
                        "reviewer registry found at the deprecated path `{}`; rename it to `{}` at the repository root. The old location still works for now but will stop being read in a future release.",
                        LEGACY_REGISTRY_RELPATH,
                        REGISTRY_FILE,
                    );
                }
                Self::load_layer(&found.path, extra_includes)?
            }
            None => Self::layer_from_includes(extra_includes)?,
        };

        // Snapshot the repo-only effective state before the user registry is
        // layered in, so the attestation binding (the hash) excludes personal
        // reviewers. The original names are kept separately so they can be
        // resolved to their post-merge form (a repo-side collision is renamed to
        // `repo:<name>` by `layer_user`) below.
        let config_hash = config.effective_hash();
        let attestations_enabled = config.attestations;
        let original_repo_names: std::collections::BTreeSet<String> =
            config.reviewers.iter().map(|r| r.name.clone()).collect();

        let mut user_files = LayerFiles::default();
        if let Some(path) = &user {
            let (user_config, files) = Self::load_layer(path, &[])?;
            user_files = files;
            config.layer_user(user_config);
            // The two registries are validated independently; re-validate the merged
            // set so a name that still collides after scoping (a pathological pair)
            // fails closed rather than overwriting a run-store directory.
            config.validate()?;
        }

        // Resolve each original repo reviewer name to its post-merge form: either
        // unchanged, or scoped to `repo:<name>` if `layer_user` renamed it to
        // resolve a collision with a same-named user reviewer.
        let reviewers = original_repo_names
            .into_iter()
            .map(|name| {
                let scoped = format!("{REPO_SCOPE_PREFIX}{name}");
                if config.reviewers.iter().any(|r| r.name == scoped) {
                    scoped
                } else {
                    name
                }
            })
            .collect();

        let attestation = RepoAttestation {
            config_hash,
            reviewers,
            attestations_enabled,
        };

        Ok((
            Sources {
                repo,
                repo_files,
                user,
                user_files,
            },
            attestation,
            config,
        ))
    }

    /// A stable, lowercase-hex SHA-256 hash of this config's "effective"
    /// reviewer set: [`Config::attestations`] plus every reviewer, fully
    /// resolved (loading applies each file's `defaults`, inlines prompt files,
    /// and merges includes before a `Config` exists).
    ///
    /// Field order in the hashed struct (`attestations` then `reviewers`) is
    /// the canonical form: loading always resolves first, and `serde_json`'s
    /// struct serialization preserves declaration order, so this hash is
    /// reproducible across processes without any separate canonicalization
    /// step. Because prompts and includes are resolved into content, the hash
    /// binds what the reviewers actually say, not the file layout: editing a
    /// prompt file moves it, while splitting an unchanged registry across
    /// includes does not. Used to bind an attestation bundle to the exact
    /// reviewer policy that produced it: a hash change (a reviewer edited,
    /// added, or removed, or `attestations` flipped) invalidates every bundle
    /// sealed under the old policy.
    #[must_use]
    pub fn effective_hash(&self) -> String {
        #[derive(Serialize)]
        struct Hashed<'a> {
            attestations: bool,
            reviewers: &'a [Reviewer],
        }
        let hashed = Hashed {
            attestations: self.attestations,
            reviewers: &self.reviewers,
        };
        #[expect(
            clippy::expect_used,
            reason = "Config's reviewers are already loaded, so they serialize"
        )]
        let bytes = serde_json::to_vec(&hashed)
            .expect("Config's reviewers are already loaded, so they serialize");
        let digest = sha2::Sha256::digest(&bytes);
        hex::encode(digest)
    }

    /// Layer a user-level registry onto this repository registry, merging the two
    /// reviewer lists into a set.
    ///
    /// Each registry resolves its own [`Defaults`], prompt files, and includes at
    /// load time (before a `Config` exists), so the reviewers in both lists
    /// already carry their effective `model`/`effort` and prompt text; layering
    /// compares and combines the effective configs. For each user reviewer, by
    /// name against the repo:
    ///
    /// - **No repo reviewer of that name:** the user reviewer is appended.
    /// - **A repo reviewer with an identical config:** the two are the same reviewer,
    ///   so the pair is deduplicated to the single repo copy (the user's is dropped).
    /// - **A repo reviewer with a different config:** a genuine collision of two
    ///   independently authored reviewers. Both are kept; the user's keeps the plain
    ///   name and the repo's is scoped to [`REPO_SCOPE_PREFIX`]`<name>` so the names
    ///   stay unique. Since the repo and user files are governed separately, neither
    ///   silently wins: a local run sees both.
    ///
    /// The combined list is re-validated by the caller, so a scoped name that still
    /// collides (a pathological registry) fails closed rather than overwriting.
    fn layer_user(&mut self, user: Config) {
        use std::collections::{BTreeMap, BTreeSet};

        // Decide what to append and which repo reviewers to scope. The repo index
        // borrows `self.reviewers`, so it is scoped to this block: the borrow ends at
        // the closing brace, freeing the mutable rename pass below to reborrow.
        let (append, scope): (Vec<Reviewer>, BTreeSet<String>) = {
            // Index the repo (base) reviewers by name to test collisions and equality.
            let repo: BTreeMap<&str, &Reviewer> = self
                .reviewers
                .iter()
                .map(|r| (r.name.as_str(), r))
                .collect();

            let mut append = Vec::new();
            let mut scope = BTreeSet::new();
            for reviewer in &user.reviewers {
                match repo.get(reviewer.name.as_str()) {
                    // Same name, same config: the identical reviewer defined in both
                    // files. Keep the single repo copy; drop the user duplicate.
                    Some(existing) if **existing == *reviewer => {}
                    // Same name, different config: a real collision. Keep the user
                    // reviewer as-is and mark the repo side for scoping below.
                    Some(_) => {
                        scope.insert(reviewer.name.clone());
                        append.push(reviewer.clone());
                    }
                    // Novel reviewer: append it.
                    None => append.push(reviewer.clone()),
                }
            }
            (append, scope)
        };

        for reviewer in &mut self.reviewers {
            if scope.contains(&reviewer.name) {
                reviewer.name = format!("{REPO_SCOPE_PREFIX}{}", reviewer.name);
            }
        }
        self.reviewers.extend(append);
    }

    fn validate(&self) -> Result<()> {
        let mut seen = std::collections::BTreeSet::new();
        let mut seen_components = std::collections::BTreeSet::new();
        for reviewer in &self.reviewers {
            if !seen.insert(reviewer.name.as_str()) {
                bail!("duplicate reviewer name: {}", reviewer.name);
            }
            // An all-whitespace prompt reviews nothing. Inline it is a typo; via a
            // prompt file it is an empty or forgotten file. Either way, fail at
            // load rather than spend a model call on a reviewer with no
            // instruction.
            if reviewer.prompt.trim().is_empty() {
                bail!(
                    "reviewer '{}' has an empty prompt; write the review instruction \
                     inline or point `prompt: {{file: ...}}` at a non-empty file",
                    reviewer.name
                );
            }
            // A reviewer name becomes a directory component in the run store, mapped
            // to a portable form first (`crate::paths`). Two distinct names that map
            // to the same component, or a degenerate one that escapes or names the
            // directory itself, would let one run clobber another's saved transcript
            // and verdict. Catch both here so a name collision fails closed at load
            // rather than silently overwriting at persist time.
            let component = crate::paths::path_component(&reviewer.name);
            if component.is_empty() || component == "." || component == ".." {
                bail!(
                    "reviewer name '{}' is not a usable run-store directory name; \
                     give it a plain name",
                    reviewer.name
                );
            }
            if !seen_components.insert(component.clone()) {
                bail!(
                    "reviewer '{}' collides with another reviewer once names are \
                     reduced to the run-store path component '{component}'; rename one",
                    reviewer.name
                );
            }
            // A model id means something only to the backend it names, so it only
            // makes sense once the backend is pinned. Reject a model under
            // `backend: any` (fail closed at the boundary) rather than letting, say,
            // a Codex id reach Claude Code once `any` resolves. This fires for an
            // inherited default model too, since `apply_defaults` ran first.
            if reviewer.model.is_some() && reviewer.backend == Backend::Any {
                bail!(
                    "reviewer '{}' sets a model but leaves backend: any; a model id is \
                     backend-specific, so pin a backend (claude-code or codex)",
                    reviewer.name
                );
            }
        }
        Ok(())
    }
}

impl Loader {
    fn new() -> Self {
        Loader {
            visited: BTreeSet::new(),
            files: LayerFiles::default(),
            origins: std::collections::BTreeMap::new(),
        }
    }

    /// Merge one parsed registry file into `config`: resolve its prompt files
    /// and fold its own `defaults` into its own reviewers (both relative to
    /// `dir`, the file's directory), append the reviewers, then recurse into its
    /// `include:` entries. `label` names the file in errors; `root` is true only
    /// for the layer's root file, the one place `attestations:` may be set.
    ///
    /// Name uniqueness across the whole layer is enforced here with both files
    /// named, rather than left to the final [`Config::validate`] backstop whose
    /// error could not say where the two definitions live.
    fn merge_file(
        &mut self,
        raw: RawFile,
        dir: &Path,
        label: &str,
        root: bool,
        config: &mut Config,
    ) -> Result<()> {
        let RawFile {
            defaults,
            attestations,
            limits,
            include,
            reviewers,
        } = raw;
        match attestations {
            Some(value) if root => config.attestations = value,
            // An included file flipping the attestation opt-in would be policy
            // hiding in a file nobody thinks of as the root; reject it rather
            // than silently ignore or honor it.
            Some(_) => bail!(
                "{label} sets `attestations`, but only the root registry file may; move the key there"
            ),
            None => {}
        }
        match limits {
            Some(value) if root => config.limits = value,
            // Same reasoning as `attestations`: a spend cap buried in an included
            // file is policy hiding away from the root. Reject it there.
            Some(_) => bail!(
                "{label} sets `limits`, but only the root registry file may; move the key there"
            ),
            None => {}
        }
        for reviewer in reviewers {
            let mut reviewer = self.resolve_prompt(reviewer, dir, label)?;
            if reviewer.model.is_none() {
                reviewer.model = defaults.model.clone();
            }
            if reviewer.effort.is_none() {
                reviewer.effort = defaults.effort.clone();
            }
            if let Some(first) = self.origins.get(&reviewer.name) {
                if first == label {
                    bail!(
                        "duplicate reviewer name: {} (declared twice in {label})",
                        reviewer.name
                    );
                }
                bail!(
                    "duplicate reviewer name: {} (declared in {first} and again \
                     in {label}); included files merge into one registry, so \
                     names must be unique across all of them",
                    reviewer.name
                );
            }
            self.origins
                .insert(reviewer.name.clone(), label.to_string());
            config.reviewers.push(reviewer);
        }
        for entry in include {
            let target = if entry.is_absolute() {
                entry
            } else {
                dir.join(entry)
            };
            self.include(&target, label, config)?;
        }
        Ok(())
    }

    /// Merge the registry file at `path` (an `include:` entry of `included_by`,
    /// or an `--include`) into `config`, then recurse into its own includes. A
    /// file already merged into this layer (a diamond include, or a cycle) is
    /// skipped, so the layer merges each file once.
    fn include(&mut self, path: &Path, included_by: &str, config: &mut Config) -> Result<()> {
        let canonical = std::fs::canonicalize(path).wrap_err_with(|| {
            format!(
                "resolving the included registry {} (from {included_by})",
                path.display()
            )
        })?;
        if !self.visited.insert(canonical) {
            return Ok(());
        }
        self.files.includes.push(path.to_path_buf());
        let raw = read_registry(path)?;
        let dir = base_dir(path);
        let label = path.display().to_string();
        self.merge_file(raw, &dir, &label, false, config)
    }

    /// Resolve a reviewer's prompt to its text: inline text passes through, and
    /// a `{file: <path>}` reference is read relative to `dir` (recorded in the
    /// layer's file trail). A missing or unreadable prompt file is an error,
    /// never an empty prompt.
    fn resolve_prompt(
        &mut self,
        reviewer: Reviewer<PromptSource>,
        dir: &Path,
        label: &str,
    ) -> Result<Reviewer> {
        let name = reviewer.name.clone();
        reviewer.map_prompt(|prompt| match prompt {
            PromptSource::Inline(text) => Ok(text),
            PromptSource::File(spec) => {
                let path = if spec.file.is_absolute() {
                    spec.file
                } else {
                    dir.join(spec.file)
                };
                let text = std::fs::read_to_string(&path).wrap_err_with(|| {
                    format!(
                        "reading the prompt file {} for reviewer '{name}' (declared in {label})",
                        path.display()
                    )
                })?;
                self.files.prompts.push(path);
                Ok(text)
            }
        })
    }
}

/// Read and parse one registry file, with path context on both failure modes.
fn read_registry(path: &Path) -> Result<RawFile> {
    let yaml = std::fs::read_to_string(path)
        .wrap_err_with(|| format!("reading reviewer registry at {}", path.display()))?;
    serde_yaml_ng::from_str(&yaml)
        .wrap_err_with(|| format!("parsing reviewer registry at {}", path.display()))
}

/// The directory a registry file's relative paths (prompt files, includes)
/// resolve against: its parent, or the current directory for a bare file name.
fn base_dir(path: &Path) -> PathBuf {
    match path.parent() {
        Some(parent) if !parent.as_os_str().is_empty() => parent.to_path_buf(),
        _ => PathBuf::from("."),
    }
}

/// A located registry file and whether it came from the deprecated location.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Found {
    /// The resolved path to the registry file.
    pub path: PathBuf,
    /// True when `path` is the deprecated [`LEGACY_REGISTRY_RELPATH`] location.
    pub deprecated: bool,
}

/// The registry sources layered into a merged config: the repository registry
/// (found by walking up from the start directory) and the user-level registry (in
/// the platform config directory). Either may be absent, but a successful
/// [`Config::discover_merged_located`] always loaded at least one file (a root
/// registry or an `--include`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Sources {
    /// The repository registry root, if one was found in an ancestor directory.
    pub repo: Option<Found>,
    /// Files beyond the root that fed the repository layer: `include:` entries,
    /// `--include` files, and prompt files. Non-empty even when `repo` is `None`
    /// if the layer was assembled purely from `--include`.
    pub repo_files: LayerFiles,
    /// The user-level registry root, if one was found in the config directory.
    pub user: Option<PathBuf>,
    /// Files beyond the root that fed the user layer.
    pub user_files: LayerFiles,
}

/// The repository-only attestation-relevant facts discovery exposes, alongside
/// the merged config, from [`Config::discover_merged_attested`].
///
/// Kept separate from [`Sources`] because it describes the *content* discovery
/// resolved (the hash, the reviewer set, the opt-in flag) rather than the
/// *files* it read from. A caller building a run seal needs this to know which
/// resolved reviewer events are eligible to be sealed (`reviewers`) and what
/// config hash to bind (`config_hash`); the `bastion attest` path also needs
/// `attestations_enabled` to know whether the repository has opted in at all.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepoAttestation {
    /// [`Config::effective_hash`] of the repository-only config (before the
    /// user-level registry is layered in).
    pub config_hash: String,
    /// The names of the reviewers the repository registry defines, after
    /// `layer_user` scoping (a repo-side collision becomes `repo:<name>`). A
    /// user-level-only reviewer is never in this set.
    pub reviewers: std::collections::BTreeSet<String>,
    /// Whether the repository registry sets `attestations: true`.
    pub attestations_enabled: bool,
}

/// Locate the registry file by walking up from `start`.
///
/// Returns the path to the first registry found in an ancestor directory, or
/// `None` if none exists up to the filesystem root. Within a single directory the
/// `.bastion.yaml` spelling wins over `.bastion.yml`, and both win over the
/// deprecated `bastion/reviewers.yaml`; a closer ancestor wins over a farther one.
///
/// # Errors
///
/// Propagates a non-`NotFound` stat error, as [`locate_kind`] does.
pub fn locate(start: &Path) -> Result<Option<PathBuf>> {
    Ok(locate_kind(start)?.map(|found| found.path))
}

/// Whether a registry candidate is present at `path`.
///
/// Only a `NotFound` result means "absent"; any other stat error (a permission
/// problem, say) is propagated with path context rather than read as absence, so a
/// registry whose presence cannot be determined fails discovery closed instead of
/// vanishing. A path that exists but is not a loadable file (a directory of that
/// name, say) still counts as present here, so discovery returns it and the
/// subsequent [`Config::load`] fails closed with a clear read error rather than the
/// candidate being silently skipped.
fn registry_present(path: &Path) -> Result<bool> {
    path.try_exists()
        .wrap_err_with(|| format!("checking for a reviewer registry at {}", path.display()))
}

/// Locate a user-level registry inside `dir`, a single directory with no ancestor
/// walk (a user config directory is a flat location, not a tree). Within it the
/// `.bastion.yaml` spelling wins over `.bastion.yml`, the same precedence
/// [`locate_kind`] applies per directory. The deprecated `bastion/reviewers.yaml`
/// shim is repository-only and not honored here.
///
/// # Errors
///
/// Returns an error if a candidate path cannot be inspected for a reason other than
/// not existing (a stat error such as a permission problem). Such an error is
/// propagated rather than read as "no registry", so a user-level gate reviewer is
/// never silently dropped because its registry could not be stat'ed or could not be
/// loaded: discovery fails closed.
pub fn locate_user(dir: &Path) -> Result<Option<PathBuf>> {
    for name in REGISTRY_FILES {
        let candidate = dir.join(name);
        if registry_present(&candidate)? {
            return Ok(Some(candidate));
        }
    }
    Ok(None)
}

/// Like [`locate`], but also reports whether the resolved path is the deprecated
/// location, so callers can warn.
///
/// # Errors
///
/// Returns an error if a candidate path cannot be inspected for a reason other than
/// not existing (a stat error such as a permission problem); it is propagated rather
/// than read as "no registry", so a governed repository gate is never silently
/// skipped because its registry could not be inspected.
pub fn locate_kind(start: &Path) -> Result<Option<Found>> {
    for dir in start.ancestors() {
        for name in REGISTRY_FILES {
            let candidate = dir.join(name);
            if registry_present(&candidate)? {
                return Ok(Some(Found {
                    path: candidate,
                    deprecated: false,
                }));
            }
        }
        let legacy = dir.join(LEGACY_REGISTRY_RELPATH);
        if registry_present(&legacy)? {
            return Ok(Some(Found {
                path: legacy,
                deprecated: true,
            }));
        }
    }
    Ok(None)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_a_two_reviewer_registry() {
        let yaml = r"
reviewers:
  - name: file-responsibility
    trigger: [src/**/*.ts]
    mode: gate
    prompt: Check single responsibility.
  - name: api-compatibility
    trigger: [src/server/**, src/client/**]
    mode: gate
    prompt: Check API compatibility.
";
        let config = Config::from_yaml(yaml, Path::new(".")).expect("valid registry");
        assert_eq!(config.reviewers.len(), 2);
        assert_eq!(config.reviewers[0].name, "file-responsibility");
    }

    #[test]
    fn rejects_duplicate_reviewer_names() {
        let yaml = r"
reviewers:
  - name: dup
    trigger: [a]
    mode: gate
    prompt: one
  - name: dup
    trigger: [b]
    mode: advisor
    prompt: two
";
        let err = Config::from_yaml(yaml, Path::new(".")).unwrap_err();
        assert!(err.to_string().contains("duplicate reviewer name"));
    }

    #[test]
    fn registry_defaults_fill_unset_reviewer_fields_and_explicit_values_win() {
        let yaml = r"
defaults:
  model: gpt-5
  effort: high
reviewers:
  - name: inherits
    trigger: [src/**]
    mode: gate
    backend: codex
    prompt: p
  - name: overrides
    trigger: [src/**]
    mode: gate
    backend: codex
    model: gpt-5-codex
    effort: low
    prompt: p
";
        let config = Config::from_yaml(yaml, Path::new(".")).expect("valid registry");
        let inherits = &config.reviewers[0];
        assert_eq!(inherits.model.as_ref().map(ModelId::as_str), Some("gpt-5"));
        assert_eq!(inherits.effort.as_ref().map(Effort::as_str), Some("high"));
        let overrides = &config.reviewers[1];
        assert_eq!(
            overrides.model.as_ref().map(ModelId::as_str),
            Some("gpt-5-codex")
        );
        assert_eq!(overrides.effort.as_ref().map(Effort::as_str), Some("low"));
    }

    #[test]
    fn a_model_under_backend_any_is_rejected() {
        let yaml = r"
reviewers:
  - name: stray
    trigger: [src/**]
    mode: gate
    model: gpt-5
    prompt: p
";
        let err = Config::from_yaml(yaml, Path::new(".")).unwrap_err();
        assert!(
            err.to_string().contains("backend: any"),
            "error should explain the model needs a pinned backend, got: {err}"
        );
    }

    #[test]
    fn an_inherited_default_model_under_backend_any_is_also_rejected() {
        // The guard fires after defaults resolve, so a default model folded into a
        // `backend: any` reviewer is caught too.
        let yaml = r"
defaults:
  model: gpt-5
reviewers:
  - name: stray
    trigger: [src/**]
    mode: gate
    prompt: p
";
        let err = Config::from_yaml(yaml, Path::new(".")).unwrap_err();
        assert!(err.to_string().contains("backend: any"));
    }

    #[test]
    fn rejects_an_unknown_reviewer_field() {
        // A misspelled or stray key is a mistake, not a no-op: `deny_unknown_fields`
        // turns it into a clear load error rather than silently ignoring it.
        let yaml = r"
reviewers:
  - name: typo
    trigger: [src/**]
    mode: gate
    bakend: codex
    prompt: p
";
        let err = Config::from_yaml(yaml, Path::new(".")).unwrap_err();
        assert!(
            format!("{err:#}").contains("unknown field `bakend`"),
            "error should name the unknown field, got: {err:#}"
        );
    }

    #[test]
    fn rejects_an_unknown_top_level_field() {
        // `reviewer:` instead of `reviewers:` would otherwise parse to an empty
        // registry and silently review nothing; reject it at the boundary.
        let yaml = r"
reviewer:
  - name: oops
    trigger: [src/**]
    mode: gate
    prompt: p
";
        let err = Config::from_yaml(yaml, Path::new(".")).unwrap_err();
        assert!(
            format!("{err:#}").contains("unknown field `reviewer`"),
            "error should name the unknown top-level field, got: {err:#}"
        );
    }

    #[test]
    fn discovers_registry_in_an_ancestor_directory() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILE),
            "reviewers:\n  - name: r\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let nested = tmp.path().join("src").join("deep");
        std::fs::create_dir_all(&nested).unwrap();

        let config = Config::discover(&nested).expect("found via ancestor walk");
        assert_eq!(config.reviewers.len(), 1);
    }

    #[test]
    fn discovers_the_yml_spelling_too() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILES[1]),
            "reviewers:\n  - name: r\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let config = Config::discover(tmp.path()).expect("found via .yml spelling");
        assert_eq!(config.reviewers.len(), 1);
    }

    #[test]
    fn the_yaml_spelling_wins_when_both_exist() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILES[0]),
            "reviewers:\n  - name: from-yaml\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILES[1]),
            "reviewers:\n  - name: from-yml\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let config = Config::discover(tmp.path()).expect("found, .yaml wins");
        assert_eq!(config.reviewers[0].name, "from-yaml");
    }

    #[test]
    fn discovers_the_deprecated_legacy_location() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join("bastion")).unwrap();
        std::fs::write(
            tmp.path().join(LEGACY_REGISTRY_RELPATH),
            "reviewers:\n  - name: legacy\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        // It resolves and loads.
        let config = Config::discover(tmp.path()).expect("legacy registry still discovered");
        assert_eq!(config.reviewers[0].name, "legacy");

        // ...and it is flagged as deprecated so the caller can warn.
        let found = locate_kind(tmp.path())
            .expect("stat ok")
            .expect("legacy located");
        assert!(found.deprecated, "legacy path must be flagged deprecated");
        assert!(found.path.ends_with("reviewers.yaml"));
    }

    #[test]
    fn the_root_registry_wins_over_the_legacy_location() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILE),
            "reviewers:\n  - name: from-root\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();
        std::fs::create_dir_all(tmp.path().join("bastion")).unwrap();
        std::fs::write(
            tmp.path().join(LEGACY_REGISTRY_RELPATH),
            "reviewers:\n  - name: from-legacy\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let found = locate_kind(tmp.path()).expect("stat ok").expect("located");
        assert!(
            !found.deprecated,
            "the root .bastion.yaml must win over the legacy path"
        );
        let config = Config::discover(tmp.path()).expect("loads the root registry");
        assert_eq!(config.reviewers[0].name, "from-root");
    }

    #[test]
    fn discovery_fails_clearly_when_absent() {
        let tmp = tempfile::tempdir().unwrap();
        let err = Config::discover(tmp.path()).unwrap_err();
        assert!(err.to_string().contains("no reviewer registry found"));
    }

    /// Write `yaml` as a `.bastion.yaml` into a fresh temp dir and return both.
    fn registry_dir(yaml: &str) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(REGISTRY_FILE), yaml).unwrap();
        dir
    }

    /// A one-reviewer registry body with `name` and `prompt` filled in.
    fn reviewer_yaml(name: &str, prompt: &str) -> String {
        format!(
            "reviewers:\n  - name: {name}\n    trigger: [src/**]\n    mode: gate\n    prompt: {prompt}\n"
        )
    }

    #[test]
    fn a_prompt_file_resolves_relative_to_the_declaring_registry() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir(dir.path().join("prompts")).unwrap();
        std::fs::write(
            dir.path().join("prompts/check.md"),
            "Check the tenant isolation.\n",
        )
        .unwrap();
        std::fs::write(
            dir.path().join(REGISTRY_FILE),
            "reviewers:\n  - name: r\n    trigger: [src/**]\n    mode: gate\n    prompt: {file: prompts/check.md}\n",
        )
        .unwrap();

        let config = Config::load(&dir.path().join(REGISTRY_FILE)).expect("loads");
        assert_eq!(config.reviewers[0].prompt, "Check the tenant isolation.\n");
    }

    #[test]
    fn a_missing_prompt_file_fails_closed_naming_the_reviewer() {
        let dir = registry_dir(
            "reviewers:\n  - name: r\n    trigger: [src/**]\n    mode: gate\n    prompt: {file: nope.md}\n",
        );
        let err = Config::load(&dir.path().join(REGISTRY_FILE)).unwrap_err();
        let rendered = format!("{err:#}");
        assert!(
            rendered.contains("prompt file") && rendered.contains("'r'"),
            "the error should name the prompt file and the reviewer, got: {rendered}"
        );
    }

    #[test]
    fn an_empty_prompt_file_is_rejected() {
        let dir = registry_dir(
            "reviewers:\n  - name: r\n    trigger: [src/**]\n    mode: gate\n    prompt: {file: empty.md}\n",
        );
        std::fs::write(dir.path().join("empty.md"), "  \n\n").unwrap();
        let err = Config::load(&dir.path().join(REGISTRY_FILE)).unwrap_err();
        assert!(format!("{err:#}").contains("empty prompt"), "got: {err:#}");
    }

    #[test]
    fn an_include_merges_after_the_including_files_reviewers() {
        let dir = registry_dir(&format!(
            "include: [extra.yaml]\n{}",
            reviewer_yaml("first", "p1")
        ));
        std::fs::write(dir.path().join("extra.yaml"), reviewer_yaml("second", "p2")).unwrap();

        let config = Config::load(&dir.path().join(REGISTRY_FILE)).expect("loads");
        let names: Vec<&str> = config.reviewers.iter().map(|r| r.name.as_str()).collect();
        assert_eq!(names, ["first", "second"]);
    }

    #[test]
    fn includes_recurse_and_resolve_relative_to_each_file() {
        // Root includes nested/mid.yaml; mid includes deep.yaml (relative to
        // nested/) and reads its prompt from a file (also relative to nested/).
        let dir = registry_dir("include: [nested/mid.yaml]\nreviewers: []\n");
        std::fs::create_dir(dir.path().join("nested")).unwrap();
        std::fs::write(
            dir.path().join("nested/mid.yaml"),
            "include: [deep.yaml]\nreviewers:\n  - name: mid\n    trigger: [src/**]\n    mode: gate\n    prompt: {file: mid.md}\n",
        )
        .unwrap();
        std::fs::write(dir.path().join("nested/mid.md"), "Mid prompt.\n").unwrap();
        std::fs::write(
            dir.path().join("nested/deep.yaml"),
            reviewer_yaml("deep", "p"),
        )
        .unwrap();

        let (config, files) = Config::load_layer(&dir.path().join(REGISTRY_FILE), &[]).unwrap();
        let names: Vec<&str> = config.reviewers.iter().map(|r| r.name.as_str()).collect();
        assert_eq!(names, ["mid", "deep"]);
        assert_eq!(config.reviewers[0].prompt, "Mid prompt.\n");
        assert_eq!(files.includes.len(), 2, "both included files are recorded");
        assert_eq!(files.prompts.len(), 1, "the prompt file is recorded");
    }

    #[test]
    fn a_diamond_include_merges_the_shared_file_once() {
        // Root includes a.yaml and b.yaml; both include shared.yaml. The shared
        // reviewer must appear once, not trip the duplicate-name check.
        let dir = registry_dir("include: [a.yaml, b.yaml]\nreviewers: []\n");
        std::fs::write(
            dir.path().join("a.yaml"),
            format!("include: [shared.yaml]\n{}", reviewer_yaml("a", "p")),
        )
        .unwrap();
        std::fs::write(
            dir.path().join("b.yaml"),
            format!("include: [shared.yaml]\n{}", reviewer_yaml("b", "p")),
        )
        .unwrap();
        std::fs::write(dir.path().join("shared.yaml"), reviewer_yaml("shared", "p")).unwrap();

        let config = Config::load(&dir.path().join(REGISTRY_FILE)).expect("loads");
        let names: Vec<&str> = config.reviewers.iter().map(|r| r.name.as_str()).collect();
        assert_eq!(names, ["a", "shared", "b"]);
    }

    #[test]
    fn an_include_cycle_terminates() {
        // a includes b, b includes a: the already-merged file is skipped, so the
        // load terminates with each file's reviewers merged once.
        let dir = registry_dir(&format!(
            "include: [a.yaml]\n{}",
            reviewer_yaml("root", "p")
        ));
        std::fs::write(
            dir.path().join("a.yaml"),
            format!("include: [b.yaml]\n{}", reviewer_yaml("a", "p")),
        )
        .unwrap();
        std::fs::write(
            dir.path().join("b.yaml"),
            format!(
                "include: [a.yaml, {REGISTRY_FILE}]\n{}",
                reviewer_yaml("b", "p")
            ),
        )
        .unwrap();

        let config = Config::load(&dir.path().join(REGISTRY_FILE)).expect("loads");
        let names: Vec<&str> = config.reviewers.iter().map(|r| r.name.as_str()).collect();
        assert_eq!(names, ["root", "a", "b"]);
    }

    #[test]
    fn a_duplicate_name_across_included_files_names_both_files() {
        let dir = registry_dir(&format!(
            "include: [extra.yaml]\n{}",
            reviewer_yaml("dup", "p1")
        ));
        std::fs::write(dir.path().join("extra.yaml"), reviewer_yaml("dup", "p2")).unwrap();

        let err = Config::load(&dir.path().join(REGISTRY_FILE)).unwrap_err();
        let rendered = format!("{err:#}");
        assert!(
            rendered.contains("duplicate reviewer name")
                && rendered.contains(REGISTRY_FILE)
                && rendered.contains("extra.yaml"),
            "the error should name the duplicate and both files, got: {rendered}"
        );
    }

    #[test]
    fn a_duplicate_name_within_one_file_says_so() {
        let dir = registry_dir(&format!(
            "{}{}",
            reviewer_yaml("dup", "p1"),
            "  - name: dup\n    trigger: [src/**]\n    mode: gate\n    prompt: p2\n"
        ));
        let err = Config::load(&dir.path().join(REGISTRY_FILE)).unwrap_err();
        let rendered = format!("{err:#}");
        assert!(
            rendered.contains("declared twice in"),
            "a same-file duplicate reads as one file, got: {rendered}"
        );
    }

    #[test]
    fn a_missing_include_fails_closed() {
        let dir = registry_dir("include: [nope.yaml]\nreviewers: []\n");
        let err = Config::load(&dir.path().join(REGISTRY_FILE)).unwrap_err();
        assert!(
            format!("{err:#}").contains("nope.yaml"),
            "the error should name the missing include, got: {err:#}"
        );
    }

    #[test]
    fn an_included_file_may_not_set_attestations() {
        let dir = registry_dir("include: [extra.yaml]\nreviewers: []\n");
        std::fs::write(
            dir.path().join("extra.yaml"),
            format!("attestations: true\n{}", reviewer_yaml("r", "p")),
        )
        .unwrap();

        let err = Config::load(&dir.path().join(REGISTRY_FILE)).unwrap_err();
        assert!(
            format!("{err:#}").contains("only the root registry file may"),
            "got: {err:#}"
        );
    }

    #[test]
    fn defaults_apply_per_file_not_across_includes() {
        // The root's defaults must not leak into the included file's reviewers,
        // and vice versa: each file is self-contained.
        let dir = registry_dir(
            "defaults:\n  model: gpt-5\n  effort: high\ninclude: [extra.yaml]\nreviewers:\n  - name: root-r\n    trigger: [src/**]\n    mode: gate\n    backend: codex\n    prompt: p\n",
        );
        std::fs::write(
            dir.path().join("extra.yaml"),
            "defaults:\n  effort: low\nreviewers:\n  - name: extra-r\n    trigger: [src/**]\n    mode: gate\n    backend: codex\n    prompt: p\n",
        )
        .unwrap();

        let config = Config::load(&dir.path().join(REGISTRY_FILE)).expect("loads");
        let root_r = &config.reviewers[0];
        assert_eq!(root_r.model.as_ref().map(ModelId::as_str), Some("gpt-5"));
        assert_eq!(root_r.effort.as_ref().map(Effort::as_str), Some("high"));
        let extra_r = &config.reviewers[1];
        assert_eq!(extra_r.model, None, "the root default must not leak in");
        assert_eq!(extra_r.effort.as_ref().map(Effort::as_str), Some("low"));
    }

    #[test]
    fn extra_includes_merge_as_if_listed_by_the_root_file() {
        let dir = registry_dir(&reviewer_yaml("root", "p"));
        let extra = tempfile::tempdir().unwrap();
        let extra_file = extra.path().join("mine.yaml");
        std::fs::write(&extra_file, reviewer_yaml("mine", "p")).unwrap();

        let (config, files) = Config::load_layer(
            &dir.path().join(REGISTRY_FILE),
            std::slice::from_ref(&extra_file),
        )
        .unwrap();
        let names: Vec<&str> = config.reviewers.iter().map(|r| r.name.as_str()).collect();
        assert_eq!(names, ["root", "mine"]);
        assert_eq!(files.includes, [extra_file]);
    }

    #[test]
    fn discovery_accepts_extra_includes_without_any_root_registry() {
        // A repo that has not adopted Bastion, reviewed with explicitly passed
        // files: the extra includes form the repository layer on their own.
        let empty = tempfile::tempdir().unwrap();
        let extra = tempfile::tempdir().unwrap();
        let extra_file = extra.path().join("mine.yaml");
        std::fs::write(&extra_file, reviewer_yaml("mine", "p")).unwrap();

        let (sources, _, config) =
            Config::discover_merged_attested(empty.path(), None, std::slice::from_ref(&extra_file))
                .unwrap();
        assert_eq!(config.reviewers.len(), 1);
        assert!(sources.repo.is_none());
        assert_eq!(sources.repo_files.includes, [extra_file]);
    }

    #[test]
    fn extra_includes_are_part_of_the_repo_attestation_hash() {
        let dir = registry_dir(&reviewer_yaml("root", "p"));
        let (_, without, _) = Config::discover_merged_attested(dir.path(), None, &[]).unwrap();

        let extra = tempfile::tempdir().unwrap();
        let extra_file = extra.path().join("mine.yaml");
        std::fs::write(&extra_file, reviewer_yaml("mine", "p")).unwrap();
        let (_, with, _) =
            Config::discover_merged_attested(dir.path(), None, &[extra_file]).unwrap();

        assert_ne!(
            without.config_hash, with.config_hash,
            "extra includes change the effective repository config"
        );
        assert!(with.reviewers.contains("mine"));
    }

    #[test]
    fn a_user_level_include_merges_into_the_user_layer() {
        // The user registry's include stays a user-layer concern: its reviewer
        // merges like any user reviewer and never enters the repo attestation.
        let repo = registry_dir(REPO_YAML);
        let user = registry_dir("include: [extra.yaml]\nreviewers: []\n");
        std::fs::write(user.path().join("extra.yaml"), reviewer_yaml("mine", "p")).unwrap();

        let (sources, attestation, config) =
            Config::discover_merged_attested(repo.path(), Some(user.path()), &[]).unwrap();
        let names: Vec<&str> = config.reviewers.iter().map(|r| r.name.as_str()).collect();
        assert_eq!(names, ["tenant-isolation", "mine"]);
        assert!(!attestation.reviewers.contains("mine"));
        assert_eq!(sources.user_files.includes.len(), 1);
        assert!(sources.repo_files.is_empty());
    }

    #[test]
    fn effective_hash_is_the_same_for_an_inline_and_a_file_prompt_with_equal_text() {
        // The hash binds resolved content, not file layout: where the prompt
        // text lives must not move it.
        let inline = Config::from_yaml(
            "reviewers:\n  - name: r\n    trigger: [src/**]\n    mode: gate\n    prompt: Check it.\n",
            Path::new("."),
        )
        .unwrap();

        let dir = registry_dir(
            "reviewers:\n  - name: r\n    trigger: [src/**]\n    mode: gate\n    prompt: {file: check.md}\n",
        );
        std::fs::write(dir.path().join("check.md"), "Check it.").unwrap();
        let via_file = Config::load(&dir.path().join(REGISTRY_FILE)).unwrap();

        assert_eq!(inline.effective_hash(), via_file.effective_hash());
    }

    #[test]
    fn effective_hash_moves_when_a_prompt_file_changes() {
        let dir = registry_dir(
            "reviewers:\n  - name: r\n    trigger: [src/**]\n    mode: gate\n    prompt: {file: check.md}\n",
        );
        std::fs::write(dir.path().join("check.md"), "Check it.").unwrap();
        let before = Config::load(&dir.path().join(REGISTRY_FILE))
            .unwrap()
            .effective_hash();
        std::fs::write(dir.path().join("check.md"), "Check it differently.").unwrap();
        let after = Config::load(&dir.path().join(REGISTRY_FILE))
            .unwrap()
            .effective_hash();
        assert_ne!(
            before, after,
            "editing a prompt file edits the effective policy"
        );
    }

    #[test]
    fn effective_hash_is_the_same_split_across_includes_or_in_one_file() {
        let one_file = Config::from_yaml(
            &format!(
                "{}{}",
                reviewer_yaml("a", "p"),
                "  - name: b\n    trigger: [src/**]\n    mode: gate\n    prompt: p\n"
            ),
            Path::new("."),
        )
        .unwrap();

        let dir = registry_dir(&format!(
            "include: [extra.yaml]\n{}",
            reviewer_yaml("a", "p")
        ));
        std::fs::write(dir.path().join("extra.yaml"), reviewer_yaml("b", "p")).unwrap();
        let split = Config::load(&dir.path().join(REGISTRY_FILE)).unwrap();

        assert_eq!(one_file.effective_hash(), split.effective_hash());
    }

    #[test]
    fn user_config_dir_honors_the_env_override() {
        let tmp = tempfile::tempdir().unwrap();
        // Safety: single-threaded test; no other thread reads the environment here.
        unsafe { std::env::set_var(CONFIG_DIR_ENV, tmp.path()) };
        assert_eq!(user_config_dir().as_deref(), Some(tmp.path()));
        unsafe { std::env::remove_var(CONFIG_DIR_ENV) };
    }

    #[test]
    fn locate_user_finds_a_flat_registry_and_prefers_yaml() {
        let dir = tempfile::tempdir().unwrap();
        assert!(locate_user(dir.path()).expect("stat ok").is_none());
        std::fs::write(dir.path().join(REGISTRY_FILES[1]), "reviewers: []\n").unwrap();
        std::fs::write(dir.path().join(REGISTRY_FILES[0]), "reviewers: []\n").unwrap();
        assert!(
            locate_user(dir.path())
                .expect("stat ok")
                .expect("located")
                .ends_with(REGISTRY_FILES[0])
        );
    }

    #[test]
    fn validate_rejects_two_names_that_reduce_to_the_same_path_component() {
        // Distinct raw names that sanitize to the same run-store directory must not
        // both persist (one would clobber the other); reject at load. `repo:test` and
        // `repo-test` both reduce to `repo-test`.
        let yaml = "\
reviewers:
  - name: 'repo:test'
    trigger: [x]
    mode: gate
    prompt: p
  - name: repo-test
    trigger: [x]
    mode: gate
    prompt: p
";
        let err = Config::from_yaml(yaml, Path::new(".")).unwrap_err();
        assert!(
            err.to_string().contains("path component"),
            "expected a path-component collision error, got: {err}"
        );
    }

    #[test]
    fn validate_rejects_a_degenerate_reviewer_name() {
        // A name that reduces to the directory itself (`..`) would escape the run's
        // reviewers directory; reject it rather than write artifacts somewhere
        // surprising.
        let yaml = "reviewers:\n  - name: '..'\n    trigger: [x]\n    mode: gate\n    prompt: p\n";
        let err = Config::from_yaml(yaml, Path::new(".")).unwrap_err();
        assert!(
            err.to_string().contains("run-store directory name"),
            "got: {err}"
        );
    }

    const REPO_YAML: &str = "\
reviewers:
  - name: tenant-isolation
    trigger: [src/**]
    mode: gate
    prompt: repo prompt
";

    #[test]
    fn merge_appends_a_distinct_user_reviewer() {
        let repo = registry_dir(REPO_YAML);
        let user = registry_dir(
            "reviewers:\n  - name: my-style\n    trigger: [src/**]\n    mode: advisor\n    prompt: p\n",
        );
        let config = Config::discover_merged(repo.path(), Some(user.path())).expect("merges");
        let names: Vec<&str> = config.reviewers.iter().map(|r| r.name.as_str()).collect();
        assert_eq!(names, ["tenant-isolation", "my-style"]);
    }

    #[test]
    fn merge_works_with_only_a_user_registry() {
        // A repo that has not adopted Bastion: discovery from an empty dir finds no
        // repo registry, but the user's reviewers still run.
        let empty = tempfile::tempdir().unwrap();
        let user = registry_dir(
            "reviewers:\n  - name: my-style\n    trigger: [src/**]\n    mode: advisor\n    prompt: p\n",
        );
        let config = Config::discover_merged(empty.path(), Some(user.path())).expect("user only");
        assert_eq!(config.reviewers.len(), 1);
        assert_eq!(config.reviewers[0].name, "my-style");
    }

    #[test]
    fn merge_deduplicates_an_identical_reviewer() {
        // The same reviewer defined in both files collapses to one; no `repo:` scope,
        // since there is nothing to disambiguate.
        let repo = registry_dir(REPO_YAML);
        let user = registry_dir(REPO_YAML);
        let config = Config::discover_merged(repo.path(), Some(user.path())).expect("dedups");
        assert_eq!(config.reviewers.len(), 1);
        assert_eq!(config.reviewers[0].name, "tenant-isolation");
    }

    #[test]
    fn merge_scopes_the_repo_side_on_a_differing_collision() {
        // Same name, different prompt: a genuine collision. Both survive, the user's
        // under the plain name and the repo's scoped to `repo:`.
        let repo = registry_dir(REPO_YAML);
        let user = registry_dir(
            "reviewers:\n  - name: tenant-isolation\n    trigger: [src/**]\n    mode: gate\n    prompt: user prompt\n",
        );
        let config = Config::discover_merged(repo.path(), Some(user.path())).expect("scopes");
        let by_name: std::collections::BTreeMap<&str, &str> = config
            .reviewers
            .iter()
            .map(|r| (r.name.as_str(), r.prompt.as_str()))
            .collect();
        assert_eq!(by_name.get("tenant-isolation"), Some(&"user prompt"));
        assert_eq!(by_name.get("repo:tenant-isolation"), Some(&"repo prompt"));
    }

    #[test]
    fn merge_errors_when_neither_registry_exists() {
        let empty_repo = tempfile::tempdir().unwrap();
        let empty_user = tempfile::tempdir().unwrap();
        let err = Config::discover_merged(empty_repo.path(), Some(empty_user.path())).unwrap_err();
        assert!(err.to_string().contains("no reviewer registry found"));
        // The message points at the user config directory it also searched.
        assert!(
            err.to_string()
                .contains(&empty_user.path().display().to_string())
        );
    }

    #[test]
    fn merge_without_a_user_dir_is_repo_only_discovery() {
        let repo = registry_dir(REPO_YAML);
        let config = Config::discover_merged(repo.path(), None).expect("repo only");
        assert_eq!(config.reviewers.len(), 1);
    }

    #[test]
    fn locate_user_falls_back_to_the_yml_spelling() {
        // Only `.bastion.yml` present: the flat user-config locator still finds it.
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(REGISTRY_FILES[1]), "reviewers: []\n").unwrap();
        assert!(
            locate_user(dir.path())
                .expect("stat ok")
                .expect("located")
                .ends_with(REGISTRY_FILES[1])
        );
    }

    #[test]
    fn a_present_but_unloadable_user_registry_fails_closed() {
        // `.bastion.yaml` exists in the user config dir but as a directory, not a
        // loadable file. Discovery must not read that as "no user registry" and
        // silently drop the user's gate reviewers; it returns the path and the load
        // fails closed with a clear error.
        let user = tempfile::tempdir().unwrap();
        std::fs::create_dir(user.path().join(REGISTRY_FILE)).unwrap();
        let repo = registry_dir(REPO_YAML);
        let err = Config::discover_merged(repo.path(), Some(user.path())).unwrap_err();
        assert!(
            format!("{err:#}").contains("reviewer registry"),
            "a present-but-unloadable user registry must error, got: {err:#}"
        );
    }

    #[test]
    fn the_shipped_registry_loads_and_is_well_formed() {
        // The registry under bastion/ is load-bearing: it is what Bastion uses to
        // review its own changes locally and in CI. Guard it so an edit that makes
        // it unparseable, duplicates a name, or leaves a reviewer empty fails here
        // rather than at review time.
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(REGISTRY_FILE);
        let config = Config::load(&path).expect("shipped .bastion.yaml loads");

        assert!(
            !config.reviewers.is_empty(),
            "the shipped registry should define reviewers"
        );
        for reviewer in &config.reviewers {
            assert!(!reviewer.name.is_empty(), "reviewer name must be non-empty");
            assert!(
                !reviewer.trigger.is_empty(),
                "reviewer '{}' must declare at least one trigger glob",
                reviewer.name
            );
            assert!(
                !reviewer.prompt.trim().is_empty(),
                "reviewer '{}' must carry a prompt",
                reviewer.name
            );
        }
    }

    #[test]
    fn effective_hash_is_stable_across_identical_loads() {
        let a = Config::from_yaml(REPO_YAML, Path::new(".")).unwrap();
        let b = Config::from_yaml(REPO_YAML, Path::new(".")).unwrap();
        assert_eq!(a.effective_hash(), b.effective_hash());
    }

    #[test]
    fn effective_hash_changes_when_a_reviewer_field_changes() {
        let a = Config::from_yaml(REPO_YAML, Path::new(".")).unwrap();
        let changed = Config::from_yaml(
            "\
reviewers:
  - name: tenant-isolation
    trigger: [src/**]
    mode: gate
    prompt: a DIFFERENT prompt
",
            Path::new("."),
        )
        .unwrap();
        assert_ne!(a.effective_hash(), changed.effective_hash());
    }

    #[test]
    fn effective_hash_changes_when_the_attestations_flag_changes() {
        let off = Config::from_yaml(REPO_YAML, Path::new(".")).unwrap();
        let on =
            Config::from_yaml(&format!("attestations: true\n{REPO_YAML}"), Path::new(".")).unwrap();
        assert_ne!(off.effective_hash(), on.effective_hash());
    }

    #[test]
    fn effective_hash_ignores_the_user_level_registry() {
        // discover_merged_attested's hash is computed on the repo-only config, so
        // layering in a user registry must not move it.
        let repo = registry_dir(REPO_YAML);
        let hash_without_user = Config::from_yaml(REPO_YAML, Path::new("."))
            .unwrap()
            .effective_hash();

        let user = registry_dir(
            "reviewers:\n  - name: my-style\n    trigger: [src/**]\n    mode: advisor\n    prompt: p\n",
        );
        let (_, attestation, _) =
            Config::discover_merged_attested(repo.path(), Some(user.path()), &[]).unwrap();
        assert_eq!(attestation.config_hash, hash_without_user);
    }

    #[test]
    fn effective_hash_reflects_applied_defaults_the_same_as_writing_the_field_inline() {
        let via_defaults = Config::from_yaml(
            "\
defaults:
  model: gpt-5
reviewers:
  - name: r
    trigger: [src/**]
    mode: gate
    backend: codex
    prompt: p
",
            Path::new("."),
        )
        .unwrap();
        let inline = Config::from_yaml(
            "\
reviewers:
  - name: r
    trigger: [src/**]
    mode: gate
    backend: codex
    model: gpt-5
    prompt: p
",
            Path::new("."),
        )
        .unwrap();
        assert_eq!(via_defaults.effective_hash(), inline.effective_hash());
    }

    #[test]
    fn discover_merged_attested_reports_only_repo_reviewer_names() {
        let repo = registry_dir(REPO_YAML);
        let user = registry_dir(
            "reviewers:\n  - name: my-style\n    trigger: [src/**]\n    mode: advisor\n    prompt: p\n",
        );
        let (_, attestation, config) =
            Config::discover_merged_attested(repo.path(), Some(user.path()), &[]).unwrap();
        assert_eq!(
            config.reviewers.len(),
            2,
            "both reviewers are still merged in"
        );
        assert_eq!(
            attestation.reviewers,
            ["tenant-isolation".to_string()].into_iter().collect(),
            "the user-level reviewer must not appear in the repo attestation set"
        );
        assert!(!attestation.attestations_enabled);
    }

    #[test]
    fn discover_merged_attested_resolves_the_scoped_name_on_a_collision() {
        let repo = registry_dir(REPO_YAML);
        let user = registry_dir(
            "reviewers:\n  - name: tenant-isolation\n    trigger: [src/**]\n    mode: gate\n    prompt: user prompt\n",
        );
        let (_, attestation, _) =
            Config::discover_merged_attested(repo.path(), Some(user.path()), &[]).unwrap();
        assert_eq!(
            attestation.reviewers,
            ["repo:tenant-isolation".to_string()].into_iter().collect(),
            "the repo side of a collision is reported under its scoped name"
        );
    }

    #[test]
    fn discover_merged_attested_reports_the_attestations_flag() {
        let repo = registry_dir(&format!("attestations: true\n{REPO_YAML}"));
        let (_, attestation, _) = Config::discover_merged_attested(repo.path(), None, &[]).unwrap();
        assert!(attestation.attestations_enabled);
    }
}
